-- MySQL Script generated by MySQL Workbench
-- Tue Dec 15 14:33:13 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dibs
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dibs` ;

-- -----------------------------------------------------
-- Schema dibs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dibs` DEFAULT CHARACTER SET utf8 ;
USE `dibs` ;

-- -----------------------------------------------------
-- Table `dibs`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dibs`.`Users` ;

CREATE TABLE IF NOT EXISTS `dibs`.`Users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(32) NOT NULL,
  `Alias` VARCHAR(128) NOT NULL,
  `Password` VARCHAR(128) NOT NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC),
  UNIQUE INDEX `Alias_UNIQUE` (`Alias` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dibs`.`Resources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dibs`.`Resources` ;

CREATE TABLE IF NOT EXISTS `dibs`.`Resources` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Owner` INT NOT NULL,
  `Name` VARCHAR(128) NOT NULL,
  `Description` LONGTEXT NULL,
  PRIMARY KEY (`ID`),
  INDEX `OwnerID_idx` (`Owner` ASC),
  CONSTRAINT `OwnerID`
    FOREIGN KEY (`Owner`)
    REFERENCES `dibs`.`Users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dibs`.`Bookings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dibs`.`Bookings` ;

CREATE TABLE IF NOT EXISTS `dibs`.`Bookings` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `User` INT NOT NULL,
  `ResourceID` INT NOT NULL,
  `Start` DATETIME NOT NULL,
  `End` DATETIME NOT NULL,
  `Remarks` LONGTEXT NULL,
  PRIMARY KEY (`ID`),
  INDEX `UserID_idx` (`User` ASC),
  INDEX `ResourceID_idx` (`ResourceID` ASC),
  CONSTRAINT `UserID`
    FOREIGN KEY (`User`)
    REFERENCES `dibs`.`Users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ResourceID`
    FOREIGN KEY (`ResourceID`)
    REFERENCES `dibs`.`Resources` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dibs`.`Shares`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dibs`.`Shares` ;

CREATE TABLE IF NOT EXISTS `dibs`.`Shares` (
  `ResourceID` INT NOT NULL,
  `UserID` INT NOT NULL,
  PRIMARY KEY (`ResourceID`, `UserID`),
  INDEX `UserID_idx` (`UserID` ASC),
  CONSTRAINT `ResourceID`
    FOREIGN KEY (`ResourceID`)
    REFERENCES `dibs`.`Resources` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `dibs`.`Users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
