-- MySQL Script generated by MySQL Workbench
-- Tue Dec 15 14:33:13 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering




-- -----------------------------------------------------
-- Table "Users"
-- -----------------------------------------------------
DROP TABLE IF EXISTS "Users" CASCADE;

CREATE TABLE  "Users" (
  "ID" SERIAL NOT NULL ,
  "Username" VARCHAR(32) NOT NULL,
  "Alias" VARCHAR(128) NOT NULL,
  "Password" VARCHAR(128) NOT NULL,
  "Email" VARCHAR(45) NULL,
  PRIMARY KEY ("ID"));

ALTER TABLE "Users" OWNER TO dibsagent;

-- -----------------------------------------------------
-- Table "Resources"
-- -----------------------------------------------------
DROP TABLE IF EXISTS "Resources" CASCADE;

CREATE TABLE  "Resources" (
  "ID" SERIAL NOT NULL ,
  "Owner" INT NOT NULL,
  "Name" VARCHAR(128) NOT NULL,
  "Description" TEXT NULL,
  PRIMARY KEY ("ID"),
  CONSTRAINT "OwnerID"
    FOREIGN KEY ("Owner")
    REFERENCES "Users" ("ID")
    ON DELETE NO ACTION -- TODO cascade
    ON UPDATE NO ACTION);


ALTER TABLE "Resources" OWNER TO dibsagent;

-- -----------------------------------------------------
-- Table "Bookings"
-- -----------------------------------------------------
DROP TABLE IF EXISTS "Bookings" CASCADE;

CREATE TABLE  "Bookings" (
  "ID" SERIAL NOT NULL ,
  "User" INT NOT NULL,
  "ResourceID" INT NOT NULL,
  "Start" TIMESTAMP NOT NULL,
  "End" TIMESTAMP NOT NULL,
  "Remarks" TEXT NULL,
  PRIMARY KEY ("ID"),
  CONSTRAINT "UserID"
    FOREIGN KEY ("User")
    REFERENCES "Users" ("ID")
    ON DELETE NO ACTION --TODO This should cascade
    ON UPDATE NO ACTION,
  CONSTRAINT "ResourceID"
    FOREIGN KEY ("ResourceID")
    REFERENCES "Resources" ("ID")
    ON DELETE NO ACTION --TODO This should cascade
    ON UPDATE NO ACTION);


ALTER TABLE "Bookings" OWNER TO dibsagent;

-- -----------------------------------------------------
-- Table "Shares"
-- -----------------------------------------------------
DROP TABLE IF EXISTS "Shares" CASCADE;

CREATE TABLE  "Shares" (
  "ResourceID" INT NOT NULL,
  "UserID" INT NOT NULL,
  PRIMARY KEY ("ResourceID", "UserID"),
  CONSTRAINT "ResourceID"
    FOREIGN KEY ("ResourceID")
    REFERENCES "Resources" ("ID")
    ON DELETE NO ACTION -- TODO cascade
    ON UPDATE NO ACTION,
  CONSTRAINT "UserID"
    FOREIGN KEY ("UserID")
    REFERENCES "Users" ("ID")
    ON DELETE NO ACTION -- TODO cascade
    ON UPDATE NO ACTION);


ALTER TABLE "Shares" OWNER TO dibsagent;

-- Sequences
DROP SEQUENCE IF EXISTS "dibs.Users_ID_sequence";
CREATE SEQUENCE  "dibs.Users_ID_sequence";
DROP SEQUENCE IF EXISTS "dibs.Resources_ID_sequence";
CREATE SEQUENCE  "dibs.Resources_ID_sequence";
DROP SEQUENCE IF EXISTS "dibs.Bookings_ID_sequence";
CREATE SEQUENCE  "dibs.Bookings_ID_sequence";

-- Test data
INSERT INTO "Users" 
  ("Username", "Alias", "Password", "Email")
  VALUES
  ("admin", "God", "$2a$10$llL.U6kVd6ZJIbiWtnRqrOFLC612LTu5cXGWyu51N2u4sqaxdgUji", "a@b.com"); 
