-- MySQL Script generated by MySQL Workbench
-- Tue Dec 15 14:33:13 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema dibs
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS "dibs" CASCADE;

-- -----------------------------------------------------
-- Schema dibs
-- -----------------------------------------------------
CREATE SCHEMA  "dibs"  ;

-- -----------------------------------------------------
-- Table "dibs"."Users"
-- -----------------------------------------------------
DROP TABLE IF EXISTS "dibs"."Users" CASCADE;

CREATE TABLE  "dibs"."Users" (
  "ID" SERIAL NOT NULL ,
  "Username" VARCHAR(32) NOT NULL,
  "Alias" VARCHAR(128) NOT NULL,
  "Password" VARCHAR(128) NOT NULL,
  "Email" VARCHAR(45) NULL,
  PRIMARY KEY ("ID"));


-- -----------------------------------------------------
-- Table "dibs"."Resources"
-- -----------------------------------------------------
DROP TABLE IF EXISTS "dibs"."Resources" CASCADE;

CREATE TABLE  "dibs"."Resources" (
  "ID" SERIAL NOT NULL ,
  "Owner" INT NOT NULL,
  "Name" VARCHAR(128) NOT NULL,
  "Description" TEXT NULL,
  PRIMARY KEY ("ID"),
  CONSTRAINT "OwnerID"
    FOREIGN KEY ("Owner")
    REFERENCES "dibs"."Users" ("ID")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "dibs"."Bookings"
-- -----------------------------------------------------
DROP TABLE IF EXISTS "dibs"."Bookings" CASCADE;

CREATE TABLE  "dibs"."Bookings" (
  "ID" SERIAL NOT NULL ,
  "User" INT NOT NULL,
  "ResourceID" INT NOT NULL,
  "Start" TIMESTAMP NOT NULL,
  "End" TIMESTAMP NOT NULL,
  "Remarks" TEXT NULL,
  PRIMARY KEY ("ID"),
  CONSTRAINT "UserID"
    FOREIGN KEY ("User")
    REFERENCES "dibs"."Users" ("ID")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "ResourceID"
    FOREIGN KEY ("ResourceID")
    REFERENCES "dibs"."Resources" ("ID")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "dibs"."Shares"
-- -----------------------------------------------------
DROP TABLE IF EXISTS "dibs"."Shares" CASCADE;

CREATE TABLE  "dibs"."Shares" (
  "ResourceID" INT NOT NULL,
  "UserID" INT NOT NULL,
  PRIMARY KEY ("ResourceID", "UserID"),
  CONSTRAINT "ResourceID"
    FOREIGN KEY ("ResourceID")
    REFERENCES "dibs"."Resources" ("ID")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "UserID"
    FOREIGN KEY ("UserID")
    REFERENCES "dibs"."Users" ("ID")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


DROP SEQUENCE IF EXISTS "dibs.Users_ID_sequence";
CREATE SEQUENCE  "dibs.Users_ID_sequence";
DROP SEQUENCE IF EXISTS "dibs.Resources_ID_sequence";
CREATE SEQUENCE  "dibs.Resources_ID_sequence";
DROP SEQUENCE IF EXISTS "dibs.Bookings_ID_sequence";
CREATE SEQUENCE  "dibs.Bookings_ID_sequence";
